adapters:
   - id: ccxt
     adapter: "@mate/adapter-ccxt"
     config:
        exchanges:
           - id: binance
             api_key: "TestKey"
             api_secret: "TestSecret"
flows:
   - name: USD to cUSD
     id: USD-to-cUSD
     description: "Do some stuff, do we even need a desc -___-"
     steps:
        - type: Exchange.Swap
          adapter: ccxt
          config:
             exchange: binance
             from: USD
             to: BUSD
             maxSlippageBPS: 20
             amount: 1000
        - type: Exchange.WithdrawCrypto
          adapter: ccxt
          config:
             exchange: binance
             asset: BUSD
             chain_id: 4220
             destination_address: ...
        - type: Bridge.Swap
          adapter: squid
          config:
             from:
                chain: BSC
                asset: BUSD
             to:
                chain: CELO
                asset: cUSD
             amount: max
             maxSlippageBPS: 20
